// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SistemaAcademico.Models;
using System;

namespace SistemaAcademico.Migrations
{
    [DbContext(typeof(SistemaAcademicoContext))]
    partial class SistemaAcademicoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaAcademico.Models.Carrera", b =>
                {
                    b.Property<int>("carreraID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombreCarrera");

                    b.HasKey("carreraID");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("SistemaAcademico.Models.Estudiante", b =>
                {
                    b.Property<int>("NoControl")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Nombre");

                    b.Property<int>("carreraID");

                    b.HasKey("NoControl");

                    b.HasIndex("carreraID");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("SistemaAcademico.Models.Estudiante", b =>
                {
                    b.HasOne("SistemaAcademico.Models.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("carreraID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
